name: build
on: [workflow_dispatch]
jobs:
  build-macos-universal:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v4
      - run: ./build-macos-universal.sh
      - uses: actions/upload-artifact@v4
        with:
          name: libsnap7-1.4.2-macos-universal
          path: ./snap7-full-1.4.2/build/bin/universal-osx/
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./build-linux-x86_64.sh
      - uses: actions/upload-artifact@v4
        with:
          name: libsnap7-1.4.2-linux-x86_64
          path: ./snap7-full-1.4.2/build/bin/x86_64-linux/
  build-windows-x86_64:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v4
      - run: .\build-windows-x86_64.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: libsnap7-1.4.2-windows-x86_64
          path: .\snap7-full-1.4.2\build\bin\win64\