name: build-macos-x86_64
on: [workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: macos-latest-large
    steps:
      - uses: actions/checkout@v4
      - run: ./build-macos-x86_64.sh
      - uses: actions/upload-artifact@v4
        with:
          name: snap7-macos-x86_64
          path: ~/snap7-full-1.4.2/build/bin/x86_64-osx/