name: Release
on: 
  push:
    tags:
    - 'v*.*.*'
jobs:
  build:
    uses: ./.github/workflows/build.yaml
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: libsnap7
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "libsnap7/*"


